### PR TITLE
♻️ refactor hashedSecret

### LINKED ISSUE #103: On bootstrap, the connector writes the state of the account secret before reading and verifying it exists
# Introduction
On the first check, the node submits the account secret to the payment channel contract, an expected behaviour. However, upon restarting the node, the node resubmits its already stored secret in the smart contract, which incurs in unnecessary costs. This behaviour repeats itself every time the node is started. The following [tx](https://blockscout.com/poa/xdai/tx/0x14a5e74172268aae757036827fd43ec7aa8e6e439b7c25f9c14bae4cc3307b19) is one of the bootstrap node, whereas this [tx](https://blockscout.com/poa/xdai/tx/0x3b8e6ef19b672c4dc4dbab2da70e7aab99886d9905260dc518f52936ae38dad3) is an example of the unnecessary follow-up one. We need to make sure only the first tx goes through, and no unnecessary transactions are made by the node.

# Task Description
- [ ] Review the `_submit` method from the connector to make sure we read the value of the secret submission state before trying to pushing the on-chain transaction.

# Definition of complete
The task is considered completed when the connector is able to read the account secret locally and no longer submits it unnecessarily on every node restart.

# Testing criteria
- [ ] The node is starting and an initial payment channel opening transaction is called.
- [ ] The node is restarted and no further transactions are sent to the payment-channel contract.

### LINKED ISSUE #105: Upon a failed transaction, the connector fails to encode the ABI due extra bytes
# Introduction
After a node fails to register the account secret, the node enters a state where its off-chain (db) data does not matches the on-chain one (since the tx failed). So, after restarting the node, it will try to retrieve this data from the payment-channel, but fail to do so. This will return an encoding error generated in https://github.com/hoprnet/hopr-core-ethereum/blob/412b6cfdf6d8c31a28c4e5e07cf5c8289cced71b/src/utils/index.ts#L321-L322, mainly because the ABI to encode has `32 bytes`, the wrong length for processing the tx (as txs are stored using `27 bytes`). This can be seen by measuring the length of a given ABI (e.g. `0x488191d02e42c5da8f11d94f0c7af5350a1c97f733b9c1d1ce0b940442a4ad1e`, which has `66` (actually `64` removing `0x`) i.e. `32 bytes). 

# Task Description
- [ ] Provide a way to recover on failed transactions, either by detecting the failed state and/or preventing such state.
- [ ] Provide a better error description on encoding to showcase the mismatch nature of the tx which web3 fails to parse.

# Definition of complete
The bug is completely patched when upon a node has failed to register to our payment channel, we are able to recover gracefully either by resetting the node state and/or automatically detecting the issue and recovering.

# Testing criteria
- [ ] Upon a failed payment channel registering transaction, the node can recover and restart the tx.

# Notes
As this is a symptom of #102, to verify this one you might need to create a fake nonce to get to the state where you can replicate the bug (i.e. node started and stored secret but on-chain tx failed).

### PR DESCRIPTION
**Pull request by nionis**
Fixes #103, fixes #105

### CODE REVIEW

File: src/hashedSecret.ts [hunk 1]
```diff
@@ -10,41 +10,102 @@ import { publicKeyConvert } from 'secp256k1'
...
+
+    return this.coreConnector.hoprChannels.methods
+      .accounts(address)
+      .call()
+      .then((res) => {
+        const hashedSecret = stringToU8a(res.hashedSecret)
+
+        // true if this string is an empty bytes32
+        if (u8aEquals(hashedSecret, EMPTY_HASHED_SECRET)) {
+          return undefined
```
Comment (0xjjpa) [inline src/hashedSecret.ts:33]: My problem with this is that we are throwing away any runtime capabilities TypeScript is giving us. We are pretty much saying "mah, don't know what's this". Don't we have a better Type we can use?

File: src/hashedSecret.ts [hunk 2]
```diff
@@ -10,41 +10,102 @@ import { publicKeyConvert } from 'secp256k1'
...
-    for (let i = 0; i < GIANT_STEP_WIDTH; i++) {
-      hashedSecret = await this.coreConnector.utils.hash(hashedSecret.slice(0, HASHED_SECRET_WIDTH))
+  /**
+   * @returns a promise that resolves to a Hash if secret is found
+   */
+  private async getOffChainSecret(): Promise<Hash | undefined> {
+    try {
+      return await this.coreConnector.db.get(Buffer.from(this.coreConnector.dbKeys.OnChainSecret()))
+    } catch {
+      return undefined
```
Comment (0xjjpa) [inline src/hashedSecret.ts:47]: Same comment as before.

**Review by 0xjjpa — APPROVED** [review]
✅  Minor comments to have in mind moving forward.
